language: ruby
cache: bundler
script: 'bundle exec rake'
rvm:
  - 2.1.2
before_install:
  - gem update bundler
  - sudo apt-get update
  - sudo apt-get install -y pdftk
  - pdftk --version
notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
      - asger@8kilo.com
    on_failure: change
    on_success: never
