language: ruby
cache: bundler
script: 'bundle exec rake'
sudo: required
dist: trusty
rvm:
  - 2.2.5

before_install:
  - gem update bundler
  - sudo apt-get update
  - sudo apt-get install -y pdftk
  - sudo apt-get install -y gobject-introspection libgirepository1.0-dev libglib2.0-dev libpoppler-glib-dev
  - curl -O http://www.vips.ecs.soton.ac.uk/supported/8.4/vips-8.4.5.tar.gz
  - tar zvxf vips-8.4.5.tar.gz && cd vips-8.4.5 && ./configure && sudo make && sudo make install
  - export GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0/
  - sudo ldconfig

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
