language: ruby
cache: bundler
script: 'bundle exec rake'
sudo: required
dist: trusty
rvm:
  - 2.2.5
env:
  - LIBVIPS_VERSION_MAJOR=8 LIBVIPS_VERSION_MINOR=3 LIBVIPS_VERSION_PATCH=3 LIBVIPS_VERSION=$LIBVIPS_VERSION_MAJOR.$LIBVIPS_VERSION_MINOR.$LIBVIPS_VERSION_PATCH
before_install:
  - gem update bundler
  - sudo apt-get update
  - sudo apt-get install -y pdftk
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
      - asger@8kilo.com
    on_failure: change
    on_success: never
