language: ruby
cache: bundler
script: 'bundle exec rake'
sudo: required
dist: trusty
rvm:
  - 2.2.5
env:
  - LIBVIPS_VERSION_MAJOR=8 LIBVIPS_VERSION_MINOR=3 LIBVIPS_VERSION_PATCH=3 LIBVIPS_VERSION=$LIBVIPS_VERSION_MAJOR.$LIBVIPS_VERSION_MINOR.$LIBVIPS_VERSION_PATCH
before_install:
  - gem update bundler
  - sudo apt-get update
  - sudo apt-get install -y pdftk

  # libvips
  # Install dependencies
  - sudo apt-get update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y automake build-essential curl gobject-introspection gtk-doc-tools libglib2.0-dev libjpeg-turbo8-dev libpng12-dev libwebp-dev libtiff5-dev libexif-dev libxml2-dev swig libpango1.0-dev libmatio-dev libopenslide-dev libcfitsio3-dev
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libgif-dev librsvg2-dev libpoppler-glib-dev libfftw3-dev liblcms2-dev libpangoft2-1.0-0 liborc-0.4-dev libpoppler-glib-dev

  # Build libvips
  - curl -O http://www.vips.ecs.soton.ac.uk/supported/$LIBVIPS_VERSION_MAJOR.$LIBVIPS_VERSION_MINOR/vips-$LIBVIPS_VERSION.tar.gz
  - tar zvxf vips-$LIBVIPS_VERSION.tar.gz && cd vips-$LIBVIPS_VERSION
  - ./configure $1
  - sudo make
  - sudo make install
  - sudo ldconfig

  # Clean up
  - sudo apt-get remove -y curl automake build-essential
  - sudo apt-get autoremove -y
  - sudo apt-get autoclean
  - sudo apt-get clean
  - sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
      - asger@8kilo.com
    on_failure: change
    on_success: never
