language: ruby
cache: bundler
script: 'bundle exec rake'
rvm:
  - 1.9.3

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
      - asger@8kilo.com
    on_failure: change
    on_success: never
